### ISSUE TITLE
com.github.aggalex.Wineglass does not seem to be a Meson build directory

### ISSUE THREAD

**Issue by jazz-it** [aggalex/Wineglass#51]
I have successfully installed all dependencies, but the following errors stopped me at the second last step:

```
❯ meson configure -Dprefix=/usr
Meson configurator encountered an error:

Directory /home/madjoe/utils/com.github.aggalex.Wineglass does not seem to be a Meson build directory.
```

My environment (OS: **Linux Mint Mate 19.3 - Tricia**):
```
❯ uname -r
5.4.0-73-generic

❯ meson install
The Meson build system
Version: 0.45.1
Source dir: /home/madjoe/utils/com.github.aggalex.Wineglass
Build dir: /home/madjoe/utils/com.github.aggalex.Wineglass/install
Build type: native build
Project name: com.github.aggalex.wineglass
Native C compiler: cc (gcc 7.5.0 "cc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0")
Native Vala compiler: valac (valac 0.40.23)
Build machine cpu family: x86_64
Build machine cpu: x86_64
Message: project name and programming language
Message: Adds project arguments
Message: Include the translations module
Message: Set our translation domain
Message: Listing dependencies
Found pkg-config: /usr/bin/pkg-config (0.29.1)
Native dependency gio-unix-2.0 found: YES 2.56.4
Library posix found: YES
Native dependency granite found: YES 0.5
Message: Adds subfolders specific build system
Message: Src build
Message: Configuring desktop entry: com.github.aggalex.wineglass.desktop
Configuring com.github.aggalex.wineglass.desktop.in using configuration
Message: Configuring config file: config.vala
Configuring conf.vala using configuration
Message: Adds files to build
Message: Defines executable
Build targets in project: 6
Found ninja-1.8.2 at /usr/bin/ninja
```

**Comment by jazz-it** [comment]
Ok, I think I got this, there was one line missing before your second last line in README:

```
❯ cd install
❯ meson configure -Dprefix=/usr
```

Then it works. But after I ran the last line, then this happened:

```
❯ ninja install
[0/1] Installing files.
Installing com.github.aggalex.wineglass.desktop to /usr/share/applications/com.github.aggalex.wineglass.desktop
Traceback (most recent call last):
  File "/usr/bin/meson", line 26, in <module>
    sys.exit(main())
  File "/usr/bin/meson", line 23, in main
    return mesonmain.run(sys.argv[1:], launcher)
  File "/usr/share/meson/mesonbuild/mesonmain.py", line 318, in run
    sys.exit(run_script_command(args[1:]))
  File "/usr/share/meson/mesonbuild/mesonmain.py", line 274, in run_script_command
    return cmdfunc(cmdargs)
  File "/usr/share/meson/mesonbuild/scripts/meson_install.py", line 393, in run
    do_install(datafilename)
  File "/usr/share/meson/mesonbuild/scripts/meson_install.py", line 212, in do_install
    install_targets(d)
  File "/usr/share/meson/mesonbuild/scripts/meson_install.py", line 334, in install_targets
    do_copyfile(fname, outname)
  File "/usr/share/meson/mesonbuild/scripts/meson_install.py", line 126, in do_copyfile
    shutil.copyfile(from_file, to_file)
  File "/usr/lib/python3.6/shutil.py", line 121, in copyfile
    with open(dst, 'wb') as fdst:
PermissionError: [Errno 13] Permission denied: '/usr/share/applications/com.github.aggalex.wineglass.desktop'
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 154, in apport_excepthook
    os.O_WRONLY | os.O_CREAT | os.O_EXCL, 0o640), 'wb') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/var/crash/_usr_share_meson_meson.1000.crash'

Original exception was:
Traceback (most recent call last):
  File "/usr/bin/meson", line 26, in <module>
    sys.exit(main())
  File "/usr/bin/meson", line 23, in main
    return mesonmain.run(sys.argv[1:], launcher)
  File "/usr/share/meson/mesonbuild/mesonmain.py", line 318, in run
    sys.exit(run_script_command(args[1:]))
  File "/usr/share/meson/mesonbuild/mesonmain.py", line 274, in run_script_command
    return cmdfunc(cmdargs)
  File "/usr/share/meson/mesonbuild/scripts/meson_install.py", line 393, in run
    do_install(datafilename)
  File "/usr/share/meson/mesonbuild/scripts/meson_install.py", line 212, in do_install
    install_targets(d)
  File "/usr/share/meson/mesonbuild/scripts/meson_install.py", line 334, in install_targets
    do_copyfile(fname, outname)
  File "/usr/share/meson/mesonbuild/scripts/meson_install.py", line 126, in do_copyfile
    shutil.copyfile(from_file, to_file)
  File "/usr/lib/python3.6/shutil.py", line 121, in copyfile
    with open(dst, 'wb') as fdst:
PermissionError: [Errno 13] Permission denied: '/usr/share/applications/com.github.aggalex.wineglass.desktop'
FAILED: meson-install 
/usr/bin/python3 /usr/bin/meson --internal install /home/madjoe/utils/com.github.aggalex.Wineglass/install/meson-private/install.dat
ninja: build stopped: subcommand failed.
```

Permission denied in `/usr/share/applications/` indicates the script needs root privileges.

I ran `sudo ninja install` and the installation completed successfully.
You may need to update your README accordingly, since it would be more accurate.
